# Generated by Django 4.1.5 on 2023-01-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.CharField(max_length=150)),
                ('group', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150, verbose_name='token')),
                ('chat_id', models.IntegerField(default=0)),
                ('chunk_size', models.IntegerField(default=1024)),
                ('cycle', models.BooleanField(default=False, verbose_name='cycle')),
                ('dont_use_proxy', models.BooleanField(default=True, verbose_name="don't use proxy")),
            ],
        ),
    ]
